name: Demo Github action

on:
  pull_request:
    branches: [main, master]
    types: [opened, reopened]

jobs:
  pre-checking:
    runs-on: ubuntu-latest

    steps:
      - name: hello world
        run: echo "Hello World"

      - name: Get PR ID
        run: printf "PR ID is ${{ github.event.pull_request }}"
