name: Demo Github action

on:
  pull_request:
    branches: [main, master]
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: hello world
        run: echo "Hello World"
