name: Demo Github action

on:
  pull_request:
    branches: [main, master]
    types: [opened, reopened]

jobs:
  pre-checking:
    runs-on: ubuntu-latest

    steps:
      - name: Initialization
        run: sudo apt-get install -y jq

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.pull_request) }}
        run: |
          echo "$GITHUB_CONTEXT"
