name: Trigger Jenkins
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Trigger Jenkins Job
        run: |
          curl --insecure -X POST ${{ secrets.JENKINS_URL }}/job/test_codai/build \
          --user '${{ secrets.JENKINS_URL }}:${{ secrets.JENKINS_API_TOKEN }}'
