name: Trigger Jenkins
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check secrets
        run: |
          echo ${{ secrets.JENKINS_URL }}
          echo ${{ secrets.JENKINS_API_TOKEN }}
          echo ${{ secrets.JENKINS_USER }}
      - name: Trigger Jenkins Job
        run: |
          curl --insecure -X POST ${{ secrets.JENKINS_URL }}/job/test_codai/build \
          --user '${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}'
