name: Trigger jenkins job
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check env
        run: |
          echo ${{ secrets.JENKINS_URL }}
          echo ${{ secrets.JENKINS_USER }}
          echo ${{ secrets.JENKINS_API_TOKEN }}
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.JENKINS_URL }}
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_API_TOKEN }}
          job: "test_codai"
