name: Lint and Comment

on:
  pull_request:
    branches: [main, master]
    types: [opened, reopened]

jobs:
  lint-and-comment:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get list of changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff --name-only HEAD^ HEAD)"
      - name: Run lint check
        shell: bash
        run: |
          echo "Command 1"
          echo "Command 2"
          echo "Command 3"
      - name: Echo
        shell: bash
        run: |
          cat lint-result.txt
