name: Lint and Comment

on:
  pull_request:
    branches: [main, master]
    types: [opened, reopened]

jobs:
  lint-and-comment:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42

      - name: Run lint check
        shell: bash
        run: |
          IFS=' ' read -r -a files <<< "$ALL_CHANGED_FILES"
          for file in "${files[@]}"; do
            echo $file
            if [[ "$file" == *.js ]]; then
              # Replace the following line with your JavaScript linter
              cp $VALIDATION_PATH/js/.eslintrc.json .
              npx eslint --resolve-plugins-relative-to=/usr/lib/node_modules -f $VALIDATION_PATH/js/formatter.js "$file" > "$file"_lint.txt || true
            elif [[ "$file" == *.py ]]; then
              # Replace the following line with your Python linter
              flake8 "$file" > lint-result.txt || true
            fi
          done
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Add comments to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require(`${process.env.VALIDATION_PATH}/script.js`);
            script(process.env.ALL_CHANGED_FILES);
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
