name: Lint and Comment

on:
  pull_request:
    branches: [main, master]
    types: [opened, reopened]

jobs:
  lint-and-comment:
    runs-on: github-runner-798f86dcc9-grsgq
    steps:
      - name: Echo
        shell: bash
        run: |
          echo hello
